-- Rename album_cover to album_image (if present) and create artist_image table
-- Works for Postgres and H2

ALTER TABLE IF EXISTS album_cover RENAME TO album_image;

CREATE TABLE IF NOT EXISTS artista_image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  artista_id BIGINT NOT NULL,
  object_key VARCHAR(1024) NOT NULL,
  content_type VARCHAR(255),
  size_bytes BIGINT,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

-- Add foreign key for artista_image
ALTER TABLE IF EXISTS artista_image
  ADD CONSTRAINT fk_artista_image_artista FOREIGN KEY (artista_id) REFERENCES artista(id);

-- Optional: create index on artista_id
CREATE INDEX IF NOT EXISTS idx_artista_image_artista_id ON artista_image(artista_id);
